package com.myspace.gestcredito.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tiempoDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("date time")
	private java.lang.String dateTime;
	@org.kie.api.definition.type.Label("time zone")
	private java.lang.String timeZone;
	@org.kie.api.definition.type.Label("unix time")
	private int unixTime;

	public tiempoDTO() {
	}

	public java.lang.String getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(java.lang.String dateTime) {
		this.dateTime = dateTime;
	}

	public java.lang.String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(java.lang.String timeZone) {
		this.timeZone = timeZone;
	}

	public int getUnixTime() {
		return this.unixTime;
	}

	public void setUnixTime(int unixTime) {
		this.unixTime = unixTime;
	}

	public tiempoDTO(java.lang.String dateTime, java.lang.String timeZone,
			int unixTime) {
		this.dateTime = dateTime;
		this.timeZone = timeZone;
		this.unixTime = unixTime;
	}

}